// frontend/src/components/UserInfo.tsx
import { useMachine } from '@xstate/react';
import { useEffect, useState } from 'preact/hooks';
import type { JSX } from 'preact/jsx-runtime';
import { authMachine } from '../state/auth';

export const UserInfo = ({ children }: { children: JSX.Element }) => {
  const [state, send] = useMachine(authMachine);
  const [isReady, setIsReady] = useState(false);

  useEffect(() => {
    setIsReady(true);
    console.log(state.matches('Logged In'));
  }, []);

  if (isReady && state.matches('Logged In')) {
    return (
      <div>
        <p>{state.context.user?.name}</p>
        <button onClick={() => send('logout')}>Logout</button>
      </div>
    );
  }

  return children;
};

// frontend/src/components/UserInfo.svelte
<script>
  import { readable } from 'svelte/store';
  import { authService } from '../state/auth/auth';

  const state = readable(authService.getSnapshot(), (set) => {
    return authService.subscribe((state) => {
      if (state.changed) {
        set(state);
      }
    }).unsubscribe;
  });
</script>

<div>
  {#if $state.matches('Logged In')}
    <p>Welcome, {$state.context.user.name}!</p>
    <button on:click={() => authService.send('LOGOUT')}>Log out</button>
  {:else}
    <button on:click={() => authService.send('AUTHENTICATE')}>Log in</button>
  {/if}
</div>
